
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app        # Mount your code for live updates
      - /app/node_modules     # Keeps container's node_modules isolated
    restart: unless-stopped
